server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.127.244:3306/baizeDB
    username: root
    password: SS111827jj!
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 39.105.127.244
    port: 6379
    timeout: 20000
    password: SS111827jj!


  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

logging:
  config: classpath:log4j2.xml



